---
cluster:
  name: "talos"
  endpoint: "https://talos.rhoades-brown.local:6443"
  endpoint_vip: 192.168.1.60

controllers:
  name_prefix: talos-controller
  a_quantity: 2
  b_quantity: 0
  start_address: 61
  cores: 2
  ram_gb: 3

workers:
  name_prefix: "talos-worker"
  a_quantity: 3
  b_quantity: 0
  start_address: 71
  cores: 4
  ram_gb: 4

proxmox:
  target_node: "proxmox"
  storage: "local-lvm"
  subnet: "192.168.1.0/24"
  gateway: "192.168.1.1"
  dns:
    - "192.168.1.21"
    - "192.168.1.22"
  search_domains:
    - "rhoades-brown.local"

argocd:
  sealed_password: "AgAYjT9yvX/Ul9o9RZg0bGa7iiEYjI/ZTbVSkmoaNcQHmfBgNDKu8CKR+63zRHlAYpdjhN9w5v9iSm88shnBXU5vXLVXZfmrEnAXrKWU4y9v7ieHXH6kXfrTfPPAEa7PGFBb2I0rPdyd14g/3yOEGraj922OGBtEgam97783H8xqJbx8ins3v+HxAhA76B8tqpXVcnqUCfjh77O9Qod6CpBuzOtlaWm8tL5kiwIT9f6xeaeEUv6Ov/ryYfhhG6BYYWEAjE72xmNRij4XAB4hrD2rLiPUsmcL4iovZxVDWu1TpsffrFAclICnWkAMRZAi7QCXXtxfybYAoaZk5zMqMNo4iic0yEpqwATZdshU83f/6WpkzK0QcEUILEcCAaQakBPtGym8uJm2lrpZBktW16bsR1T/nGJ9UgK/bz8UORxKMlVwRV4LV/9EGgiKM9tydJiAYwRLWjDzf359IpQyliTGHObk6TZIWsk99QR7OF8AUFofkrU5526U88XYpSUeMJg+8BUtCZmkClPBNjwF///edkWadldI/ggbPsTtTfJlDJUdqAUjONxTTEFmvIyZeaqmmVJwcr8l09KaNGC13Jg9WkTuhZuVY7gA3APZycQ1fWYpscMRQHuUT+hsQmaVFIzuBkR+AS1RCQ6kPezlwlaXHu++Kskj9ealcDpOUk7dJWDuZeBl6jGhX3vXg+Wuam29s8EjDv874V2o89hkBX/yT1Yc39kjNAAdCfhQlGOuXCOEkL0uM7XksDvEB8+cZxq1KUCQCCIbB6MmwyISK/HCW4V1RONPvPMB+oN0IJt1tr/an70NU00fpA2oDrE="
  sealed_type: "AgAoibspQ4q0Aj3L3Wdqs0x76z/3Ha47FZAVxAVFqcQUOvMPk2GAg/f/s3HMJj45RHt7fgM5KUQaRUlwvYUyDpdsQwgSHRdr9aRLR4vRibMegSuHLzOi8yD0DmppSrO7vPv/bLuy62oHtDzw9n0s8VxDwWZ9TYV54cMz+ubezaAPztlFM0G+VX7InGCQtT09JowRo0Xw4z9IZcDyMpB06y8NwiIKaUj42iqHCLAxvkR4/HUfpktnU40BLNpXU8EtEFAezIK6EqGAlC5reYCXJBhM4I7e7mI831ElYU9W8t2EANgE1wEXP87w4bpHWwNeP0GPFrTZrHvMAkrf+Lp7Lq7E1d3BYjlfvHUbd8cJ6R3d7h7y/oHpQ6SpqIDnKkiaG0gogfFViD6CjJW5+aJxwZu7z2lHWEgSjpct5D6Qcjdr2524gAGLKo/2D9CfHrV1KBUu6s4HlXSMbvZ0H4Hv1mNmU8viDPkFPmyayOJCIzOeqj7Pi14suihXr8eNBK7GzBK2Y+YBAFmKeSMLP5ortF5zKPoqkq678jBijCTFANE3AqWFYtCrFyjFabVpHcTWPeFZbMrwc6qizszuBsKrUNJnZs6soaPDP7tCtl2pwZ8dOUz6tvTRpozBNcH9FE+5R3FnI9wR50AXYC6L5yEeNBrsuSGcbSQKRhabz6bWrB6Dv8XFS5GyfW7qgxBdKPojHq/saNA="
  sealed_url: "AgAMB+UV7uxEXL43fSk0BDLxyqcyMkUoEVzQloFmgKc51fVY6v1CgwwciQ3KQLKi74aMH29CVvzBdHSTsk4Xpg4FwzQZS/Iy5h4l3ZagqONxk5O+Kb0oJMcobephApRju9cvEqBe7N+1m1ruIvZ65sQo6CTMx3EGeZBmI1UzvRME9BxUlxGIGAdcDFL+rdhGrmK8ec9+UC8dlEcZr14IJNf/A77urM6o5htUgZrXXGPhz8tVBj8GROf1e6FkQFeHF5LONRS/frV90Ml/KE8t7NTmho8Eed7MCGbRtP7uajGyt1L1u+g87v/fZca0QpA7IGu7tksWQCrymQmgHvDq5+ZsSGvIkM2rhmZp4lHR82FAPMjWTNSvIFzg7XX8bnxzCmesDKIueEPX3gF+8LMH6IxuFVCeqSZNrsRXYD3DuG4uBZxLd0TM8/ZhclUPEu0H1O03kDERVSKISuli9Yxk9PIIknViM0D7Sv34FX/gkVKhPH+MDRW8MTbjAZRXodXtCMi8vGtgCW4j524qoOETOdKa/kCNLdjZlachK3isOc5O6voT0lUazUa9W4mZgxzEWwJ9T8fAU0qE8C+EdBWbqk+Girr1NqJz0baujuHaWa5PZ8ygz+xYQUwc1sQrK2WTFaYkv2bU9s73CCQ3T5fS/OiXlLP/YCNt6t4AGNebq+5ndwStbQ2HPLVmbaM14UrY6w454QRR5E3bLMhHClZ3aMA0ZlwgqiGyW47sWO0mlWKHXQ=="
  sealed_username: "AgASdGwn9KD3gndcWu7BeNtg+Yi/Mg3HQ13MewLiPovQdOuLBVkvcYjmS3+ledn4lpQmFdbltgcUF2HaWdBg763PvKET5GD5OVvbYdnxSN9fqUpnWH7SSkCwqMr66UpbsqrKmmd5vkBZ4hkYJslnr+gNZepCcrdNXkzYcxk2jxdAYrIhyy7A6dqttrmLUgzVAt6gVegsNmMpuOO0PZBr6IRolLLWAlsKPDEYmVGcumFmbqXjjZNWkjd7L6de2wXr/ypl3XGNvkEd0Zm2oGqPD3giPgljoM1AxbGt8ACdNd7ZSSyrsb+xnbjUFEyOVb4BWmMaxp4qm5bjkoRTUC8OL/BjHYjxbOztYSp8B1sdgFTiDGkxR1Fu+cNfB38s1LwGJ8gSnLeExNYF3BwHAlbkxLD1+aNAtu7IBtxAgaPaSQC3asWNSUlAwJbrAIJJ9zucEo0EPgRJ5CVlMPc2LoidLxnT56VmGZRcVHCLF8WU3qCXE2+96JENdA9+O8rjBg57FNhhTINdMoMt1xDT2LvUUC/cLsxMfUVjMBzyfHEZ9kAdh6kxbXQZTdbJEVJTBnHQxMIPj3t0DpUtscbyuJ4u0kqlzE7lETgivfmbaewQ1QsaSmQ+ofXBrJUfmUxJtjy5bWcR0uGd2azsg8SdtDGDuy7W2Xa1CO+CuJx1ksqAnt92IR7S8wAdMhfWA29BP2kcOaSHs/xS+ZxmGAw20ed4"
